### ISSUE TITLE
Comments have HTML in them

### ISSUE THREAD

**Issue by matt-ewan-laws** [Livinglist/Hacki#389]
![Screenshot_2024-05-22-07-32-34-04_a4cc5d72270e66b9bb8cebf0fde3bfdf](https://github.com/Livinglist/Hacki/assets/52166117/69b66a65-247e-4fb8-9eeb-3da2c54e4c6e)

Android 13

**Comment by Livinglist** [comment]
Thanks for letting me know, I think Hacker News just updated their HTML.

**Comment by Livinglist** [comment]
keeping this issue open until the fix is out.

**Comment by Livinglist** [comment]
142 (2.7.3) has been uploaded to Google Play Store for review. It's gonna take a while before the build with fix is released on F-Droid, but see here if you can't wait: https://github.com/Livinglist/Hacki/releases/tag/v2.7.3

**Comment by matt-ewan-laws** [comment]
It's still showing in some posts.

![Screenshot_2024-05-22-18-30-23-60_a4cc5d72270e66b9bb8cebf0fde3bfdf.jpg](https://github.com/Livinglist/Hacki/assets/52166117/998c6e66-c539-4a7c-b4dc-9208179e90fd)

**Comment by Livinglist** [comment]
> It's still showing in some posts.
> 
> ![Screenshot_2024-05-22-18-30-23-60_a4cc5d72270e66b9bb8cebf0fde3bfdf.jpg](https://private-user-images.githubusercontent.com/52166117/332900540-998c6e66-c539-4a7c-b4dc-9208179e90fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTk4NTEsIm5iZiI6MTcxNjM5OTU1MSwicGF0aCI6Ii81MjE2NjExNy8zMzI5MDA1NDAtOTk4YzZlNjYtYzUzOS00YTdjLWI0ZGMtOTIwODE3OWU5MGZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE3MzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZDc4YWM2OTk3NjZkYjg2N2RkOGI5N2M0ODM2MDViNzE3MjIzODkwMjk3ZDM5MGMzMTJkZDAyNjU5NGNiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3kmdqErS9lZJRZsZruJ3qv0nSI_iuFLmKLtR8jZjAkQ)

Hi can you try clearing cache in the settings:
![IMG_2784](https://github.com/Livinglist/Hacki/assets/7277662/685c0303-08ef-4b14-a7da-1afedd53a91e)

**Comment by matt-ewan-laws** [comment]
> > It's still showing in some posts.
> 
> Hi, @matt-ewan-laws can you try clearing cache in the settings, and confirm you are on v2.7.3 by tapping on “About”. ![IMG_2784](https://private-user-images.githubusercontent.com/7277662/332902879-685c0303-08ef-4b14-a7da-1afedd53a91e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDg3NTIsIm5iZiI6MTcxNjQwODQ1MiwicGF0aCI6Ii83Mjc3NjYyLzMzMjkwMjg3OS02ODVjMDMwMy0wOGVmLTRiMTQtYTdkYS0xYWZlZGQ1M2E5MWUuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIwMDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDZkZDQ5ZWIxMjhkMjQ1NGZlNmIxNTg2Yjc2YjY0YzdmYmQ2Njk3OTFjNTYxMzMyOTUzZjAzZTgyNmRmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uwHSPxkxMY1Nc7c1rTlet6HR0PeHvJ_P660TdnxNuOA)

Yes I was being a dummy and didn't realise my attempt to install the latest had failed.

Uninstalled previous version, installed newest apk and everything appears working
